---

- include: credentials-check.yml
  tags: vsphere

- name: vSphere Cloud Controller | Generate Manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/{{ item.file }}"
  with_items:
    - {name: vsphere-config, file: vsphere-config-configmap.yml}
    - {name: vsphere-config, file: vsphere-config-secret.yml}
    - {name: vsphere-cloud-controller, file: vsphere-cloud-controller-rbac.yml}
    - {name: vsphere-cloud-controller, file: vsphere-cloud-controller.yml}
  register: vsphere_cloud_controller_manifests
  when: inventory_hostname == groups['kube-master'][0]
  tags: vsphere

- name: vSphere Cloud Controller | Apply Manifests
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/{{ item.item.file }}"
    state: "latest"
  with_items:
    - "{{ vsphere_cloud_controller_manifests.results }}"
  when:
    - inventory_hostname == groups['kube-master'][0]
    - not item is skipped
  loop_control:
    label: "{{ item.item.file }}"
  tags: vsphere
