---
- name: vSphere CSI Driver | check vsphere_vcenter_ip value
  fail:
    msg: "vsphere_vcenter_ip is missing"
  when: vsphere_vcenter_ip is not defined or not vsphere_vcenter_ip

- name: vSphere CSI Driver | check vsphere_vcenter_port value
  fail:
    msg: "vsphere_vcenter_port is missing"
  when: vsphere_vcenter_port is not defined or not vsphere_vcenter_port

- name: vSphere CSI Driver | check vsphere_user value
  fail:
    msg: "vsphere_user is missing"
  when: vsphere_user is not defined or not vsphere_user

- name: vSphere CSI Driver | check vsphere_password value
  fail:
    msg: "vsphere_password is missing"
  when: vsphere_password is not defined or not vsphere_password

- name: vSphere CSI Driver | check vsphere_datacenter value
  fail:
    msg: "vsphere_datacenter is missing"
  when: vsphere_datacenter is not defined or not vsphere_datacenter

- name: vSphere CSI Driver | check vsphere_insecure value
  fail:
    msg: "vsphere_insecure is missing"
  when: vsphere_insecure is not defined or not vsphere_insecure

- name: vSphere CSI Driver | check vsphere_cluster_id value
  fail:
    msg: "vsphere_cluster_id is missing"
  when: vsphere_cluster_id is not defined or not vsphere_cluster_id